### ISSUE TITLE
Quando a mensagem foir enviada por DM, responder por DM também.

### ISSUE THREAD

**Issue by ghost** [cadusilva/bolha-clima#4]
Alguns usuários levantaram preocupações sobre a privada dos toots do bot e o vazamento de informações geográficas. Idealmente o bot iria responder com a mesma visibilidade que o toot original perguntou.

**Comment by cadusilva** [comment]
Porém, já que se trata de um bot, o ideal é a privacidade da resposta nunca ser `pública`, mas no máximo `não-listada`.
