### ISSUE TITLE
Modo de manutenção

### ISSUE THREAD

**Issue by cadusilva** [cadusilva/bolha-clima#8]
Uma variável que ativa o modo de manutenção, quando o bot não consulta a API e simplesmente responde com uma mensagem personalizada de que está indisponível no momento ou outra razão.

**Comment by cadusilva** [comment]
Fernanda, não entendi muito bem como funciona. Do jeito que está agora, é definida a mensagem a enviar em resposta. Mas como ativar ou desativar o modo de manutenção para resposta ser disparada?

**Comment by ghost** [comment]
Basta definir a mensagem! Se houver uma mensagem de manutenção, então o sistema está em modo de manutenção. Se não houver mensagem, não há manutenção.

**Comment by cadusilva** [comment]
> Basta definir a mensagem! Se houver uma mensagem de manutenção, então o sistema está em modo de manutenção. Se não houver mensagem, não há manutenção.

Ah sim, entendi! Testei aqui e tudo certo, obrigado!
